apiVersion: "example.martin-helmich.de/v1alpha1"
kind: "Project"
metadata:
  name: "example-project"
  namespace: "default"
spec:
  replicas: 1
  env:
    - name: KUBERNETES_SERVICE_HOST
      value: "kubernetes.default.svc.cluster.local"
    - name: KUBERNETES_SERVICE_PORT
      value: "443"